name: Lint Documentation

on:
  pull_request:
    paths:
      - "docs/**/*.md"
      - "*.md"
      - ".github/**/*.md"
  push:
    branches:
      - main
    paths:
      - "docs/**/*.md"
      - "*.md"
      - ".github/**/*.md"

jobs:
  markdownlint:
    name: Lint Markdown Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '18'

      - name: Install markdownlint-cli
        run: npm install -g markdownlint-cli

      - name: Run markdownlint
        run: markdownlint '**/*.md' --ignore node_modules --ignore .git
        continue-on-error: true

  link-check:
    name: Check Markdown Links
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check links in Markdown files
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: 'yes'
          use-verbose-mode: 'no'
          config-file: '.github/markdown-link-check-config.json'
          check-modified-files-only: 'yes'
        continue-on-error: true
