name: Welcome Contributors

on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

permissions:
  issues: write
  pull-requests: write

jobs:
  welcome:
    name: Welcome New Contributors
    runs-on: ubuntu-latest

    steps:
      - name: Welcome first-time contributors
        uses: actions/first-interaction@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

          issue-message: |
            👋 Thanks for opening your first issue in StormCom!

            A maintainer will review your issue soon. In the meantime,
            please:
            - Check our [Contributing Guidelines](.github/CONTRIBUTING.md)
            - Review the [Code of Conduct](.github/CODE_OF_CONDUCT.md)
            - Browse our [Documentation](docs/) for more information

            We appreciate your contribution to making StormCom better! 🚀

          pr-message: |
            👋 Thanks for opening your first pull request in StormCom!

            A maintainer will review your PR soon. Please make sure:
            - [ ] Your PR follows our
            [Contributing Guidelines](.github/CONTRIBUTING.md)
            - [ ] All CI checks pass
            - [ ] You've added appropriate tests
            - [ ] Documentation has been updated (if needed)

            We appreciate your contribution to making StormCom better! 🚀
